### ISSUE TITLE
MOS 3.0alpha2: mos_fopen API call for Write does not work.

### ISSUE THREAD

**Issue by lennart-benschop** [AgonConsole8/agon-mos#100]
For example:

SAVE "file.bas"

does not write the file. In v2.3.2 this still works.
I got this problem also in other programs that write files via the mos_fopen API instead of mos_save.

**Comment by stevesims** [comment]
This issue has been fixed, and a commit added to the system-variables branch

I may put out a 3.0alpha2a release with this fix

**Comment by stevesims** [comment]
the 3.0 alpha 2 release has been replaced with a new release containing this fix

(a mistake was made in the previous release, so it has been deleted)
