### ISSUE TITLE
Don't push repeated commands to CLI history

### ISSUE THREAD

**Issue by stevesims** [AgonConsole8/agon-mos#24]
If the last command entered is a repeat of the one before, don't push it to history

Also consider - if the last command entered was previously entered, then _maybe_ move that command to last history entry instead of pushing a copy?

**Comment by badre2911** [comment]
I suppose that the history is put in a table (array), you just have to see if it already exists in this table, if it does not exist we do not insert it in the history table.

**Comment by stevesims** [comment]
version 2.3.0 implements the "If the last command entered is a repeat of the one before, don't push it to history" idea.

will close this for now, as the basic feature has been added.  if further refinement to how the history system works we should raise a new issue
