### ISSUE TITLE
MOS BDOS/BIOS equiv?

### ISSUE THREAD

**Issue by kristofer** [AgonConsole8/agon-mos#35]
Is there a BDOS/BIOS equivlibrary somewhere? I understand you can call all of MOS from inside BBSBASIC, but if I was to port another language to it, is there a BODS kind of interface somewhere? ANY urls or hints would be appreciated,

**Comment by stevesims** [comment]
MOS offers a relatively simple API that can be accessed easily from eZ80 assembler.

BASIC exposes _some_ of MOS functionality via things like `*FX` commands, but not all things are directly accessible, some you will need to write some assembler for.

The MOS API, as can be used from eZ80 code, is [documented here](https://agonconsole8.github.io/agon-docs/MOS-API.html)

One thing to bear in mind is that on an Agon system, much of the I/O is performed by the VDP and not MOS.  All video output (drawing operations), as well as keyboard and mouse input, is handled by the VDP, and there is a communication channel between the VDP system and MOS.  From inside BASIC, the `VDU` command is used to send things direct to the VDP - other commands such as `PRINT`, `MOVE`, `DRAW` and `PLOT` are _effectively_ just wrappers for VDU

Besides the documentation website, I'd advise joining the [Agon & Console8 Community Discord server](https://discord.gg/jDUhhUwFq9) where you'll find an active community

**Comment by kristofer** [comment]
excellent, thanks very much;
