### ISSUE TITLE
Timestamps written on files are incorrect.

### ISSUE THREAD

**Issue by lennart-benschop** [AgonConsole8/agon-mos#68]
Even if one takes the trouble to set the system time using the TIME command, files that are subsequently written get a bogus timestamp.

Like 2001/11/09 12:00 for a file that was written today (2024/05/09 19:26) TIME was set correctly and shows the correct date & time.

dir -l

does show correct timestamps on files written by an external computer. When mounting the SD card in an external computer, it shows the same bogus time stamps as Agon, for those files written on Agon.

**Comment by stevesims** [comment]
this fix was merged and released as part of 2.3.0
